RISDEV-10641 DTOs & Transformer for new citation tables (#3657)
* Add DTOs for new citation tables

RISDEV-10641

* Adjust transformer to also write to new tables

RISDEV-10641

* Move citation transformation into repository

We need to load the target decision for creating the dto and we do not
want to do this in the transformer

RISDEV-10641

* Manually manage UUIDs for activeCitations

We need to use the same id in two tables that do not have a foreign-key
relationship.

RISDEV-10641

* Simplify code

RISDEV-10641

* Order citations by rank

RISDEV-10641

* Mark citation type as nullable

RISDEV-10641

* Manually manage uuids for creation as well

RISDEV-10641

* Reference source and target using id

Due to a problem with the hibernate mapping the code was falsely
throwing:
org.springframework.orm.jpa.JpaSystemException: Don't change the reference to a collection with delete orphan enabled: de.bund.digitalservice.ris.caselaw.adapter.database.jpa.DecisionDTO.caselawCitationBlindlinks

We could figure out that this only happens when using
`referencedColumnName`. Therefore, we redesigned the tables to use the
id of the document instead.

RISDEV-10641

* Add integration test

RISDEV-10641