Reference source and target using id
Due to a problem with the hibernate mapping the code was falsely
throwing:
org.springframework.orm.jpa.JpaSystemException: Don't change the reference to a collection with delete orphan enabled: de.bund.digitalservice.ris.caselaw.adapter.database.jpa.DecisionDTO.caselawCitationBlindlinks

We could figure out that this only happens when using
`referencedColumnName`. Therefore, we redesigned the tables to use the
id of the document instead.

RISDEV-10641